env_kwargs:
  currentTurbScale: 2.0
  currentVelScale: 1.0
  noiseMagActuation: 0.1
  noiseMagCoeffs: 0.1
modelName: SAC_try6
model_kwargs:
  batch_size: 256
  buffer_size: 131072
  gamma: 0.95
  learning_rate: 0.005
  learning_starts: 256
  train_freq:
  - 1
  - step
  use_sde_at_warmup: true
  verbose: 1
nTrainingSteps: 3000000
policy_kwargs:
  activation_fn: <class 'torch.nn.modules.activation.GELU'>
  net_arch:
    pi:
    - 128
    - 128
    qf:
    - 128
    - 128
  use_sde: false
