agentName: RecurrentPPO_try0
agent_kwargs:
  batch_size: 256
  gamma: 0.95
  learning_rate: 0.0005
  verbose: 1
env_kwargs:
  currentTurbScale: 2.0
  currentVelScale: 1.0
  noiseMagActuation: 0.1
  noiseMagCoeffs: 0.1
nProc: 4
nTrainingSteps: 1500000
policy_kwargs:
  activation_fn: <class 'torch.nn.modules.activation.GELU'>
  net_arch:
    pi:
    - 128
    - 128
    - 128
    qf:
    - 128
    - 128
    - 128
trainingTime:
- 37613.163339
- 24348.610874
- 32366.512904
