agentName: SAC_try7_performanceCheck_2
agent_kwargs:
  batch_size: 256
  buffer_size: 196608
  gamma: 0.95
  learning_rate: 0.002
  learning_starts: 256
  train_freq:
  - 1
  - step
  use_sde_at_warmup: true
  verbose: 1
env_kwargs:
  currentTurbScale: 2.0
  currentVelScale: 1.0
  noiseMagActuation: 0.1
  noiseMagCoeffs: 0.1
nProc: 8
nTrainingSteps: 50000
policy_kwargs:
  activation_fn: <class 'torch.nn.modules.activation.GELU'>
  net_arch:
    pi:
    - 128
    - 128
    - 128
    qf:
    - 128
    - 128
    - 128
  use_sde: false
trainingTime: 195.05272
