modelName: SAC_try3
model_kwargs:
  action_noise:
    mu:
    - 0.0
    - 0.0
    - 0.0
    sigma:
    - 0.1
    - 0.1
    - 0.1
  batch_size: 2048
  buffer_size: 1000000
  gamma: 0.95
  learning_rate: 0.0005
  learning_starts: 1024
  train_freq:
  - 4
  - step
  use_sde_at_warmup: true
  verbose: 1
nTrainingSteps: 3000000
policy_kwargs:
  activation_fn: <class 'torch.nn.modules.activation.GELU'>
  net_arch:
    pi:
    - 64
    - 64
    qf:
    - 128
    - 128
  use_sde: false
