env_kwargs:
  currentTurbScale: 0.0
  currentVelScale: 0.5
  noiseMagActuation: 0.0
  noiseMagCoeffs: 0.0
modelName: SAC_try5_noTurb
model_kwargs:
  batch_size: 256
  buffer_size: 131072
  gamma: 0.95
  learning_rate: 0.0005
  learning_starts: 256
  train_freq:
  - 1
  - step
  use_sde_at_warmup: true
  verbose: 1
nTrainingSteps: 200000
policy_kwargs:
  activation_fn: <class 'torch.nn.modules.activation.GELU'>
  net_arch:
    pi:
    - 128
    - 128
    qf:
    - 128
    - 128
  use_sde: false
